# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndrewIDs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('andrewId', models.CharField(max_length=20)),
                ('first_voted', models.BooleanField(default=False)),
                ('second_voted', models.BooleanField(default=False)),
                ('is_judge', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('votes_first_round', models.IntegerField(default=0)),
                ('votes_second_round', models.IntegerField(default=0)),
                ('votes_judge', models.IntegerField(default=0)),
                ('information', models.CharField(max_length=8192)),
                ('picture', models.ImageField(blank=True, upload_to=b'pictures')),
                ('round', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(default=1)),
                ('open', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionid', models.CharField(max_length=128)),
                ('first_voted', models.BooleanField(default=False)),
                ('second_voted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TicketNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('first_voted', models.BooleanField(default=False)),
                ('second_voted', models.BooleanField(default=False)),
            ],
        ),
    ]
